# Generated by Django 6.0.3 on 2026-06-09 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.tourists.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("badges", "0015_touristobject_last_sync_check_osmsyncconflict"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TouristProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nickname", models.CharField(max_length=100, unique=True, verbose_name="Pseudonim (Publiczny)")),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="Data urodzenia")),
                ("club_join_dates", models.JSONField(blank=True, default=dict, verbose_name="Przynależność klubowa")),
                ("active_plan", models.CharField(default="FREE", max_length=50, verbose_name="Aktywny pakiet")),
                ("max_photos_per_ascent", models.IntegerField(default=1, verbose_name="Limit zdjęć per log")),
                ("max_active_badges", models.IntegerField(default=3, verbose_name="Limit aktywnych odznak")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tourist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Turysty",
                "verbose_name_plural": "Profile Turystów",
                "db_table": "tourists_profile",
            },
        ),
        migrations.CreateModel(
            name="AscentLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ascent_date", models.DateField(verbose_name="Data wejścia")),
                (
                    "souvenir_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.tourists.models.user_directory_path,
                        verbose_name="Zdjęcie pamiątkowe",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "peak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ascents_logged",
                        to="badges.touristobject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ascents", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Wejścia",
                "verbose_name_plural": "Logi Wejść",
                "db_table": "tourists_ascent_log",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "peak", "ascent_date"), name="unique_ascent_per_day")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBadgeProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cycle_number", models.IntegerField(default=1, verbose_name="Cykl / Edycja")),
                (
                    "domain_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Subskrybowana (Czeka na logi)"),
                            ("IN_PROGRESS", "W trakcie zdobywania"),
                            ("COMPLETED", "Skompletowana matematycznie"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "logistic_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WAITING_FOR_SEND", "Gotowa do wysyłki (Skompletowana)"),
                            ("WAITING_FOR_VERIFICATION", "Wysłana do PTTK (Weryfikacja)"),
                            ("WAITING_FOR_RECEIVING", "Zatwierdzona (Czeka na listonosza)"),
                            ("ALBUM", "Wpięta do albumu (Zakończone)"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("logistic_status_date", models.DateField(blank=True, null=True, verbose_name="Data zmiany logistyki")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progresses",
                        to="badges.badgemodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_progresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zabetonowana wersja regulaminu po pierwszym zgłoszonym wejściu.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_users",
                        to="badges.badgeversionmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postęp Odznaki (Subskrypcja)",
                "verbose_name_plural": "Postępy Odznak",
                "db_table": "tourists_badge_progress",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "badge", "cycle_number"), name="unique_active_cycle_per_badge"
                    )
                ],
            },
        ),
    ]
