# Generated by Django 6.0.3 on 2026-06-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristprofile",
            name="preferred_base_map",
            field=models.CharField(default="carto", max_length=20, verbose_name="Preferowany podkład mapy"),
        ),
    ]
