# Generated by Django 6.0.8 on 2026-08-31 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ascentlog",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="ascents", to="tourists.touristprofile"
            ),
        ),
        migrations.AlterField(
            model_name="userbadgeprogress",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="badge_progresses",
                to="tourists.touristprofile",
            ),
        ),
    ]
