# Generated by Django 6.0.8 on 2026-08-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0002_alter_organizermodel_has_publication_consent_and_more"),
        ("tourists", "0002_alter_ascentlog_profile_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ascentlog",
            index=models.Index(fields=["profile", "ascent_date"], name="ascent_profile_date_idx"),
        ),
        migrations.AddIndex(
            model_name="userbadgeprogress",
            index=models.Index(fields=["profile", "badge", "domain_status"], name="progress_p_b_s_idx"),
        ),
    ]
