# Generated by Django 6.0.8 on 2026-09-01 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.tourists.models


class Migration(migrations.Migration):
    dependencies = [
        ("tourists", "0003_ascentlog_ascent_profile_date_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ascentlog",
            name="souvenir_image",
            field=models.ImageField(
                blank=True,
                help_text="Ochrona: Django ImageField weryfikuje nagłówek obrazu (Pillow). BRAK: limit rozmiaru (DoS) oraz wyraźna walidacja MIME — zob. AUDYT-028. Upload przez API nie jest jeszcze obsługiwany (tylko Admin); przed dodaniem endpointu REST trzeba dodać validator rozmiaru + Content-Type.",
                null=True,
                upload_to=apps.tourists.models.profile_directory_path,
                verbose_name="Zdjęcie pamiątkowe",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Nazwa zdarzenia domenowego, np. 'BadgeStatusChanged', 'AscentLogged'.",
                        max_length=100,
                        verbose_name="Akcja (typ zdarzenia)",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        help_text="Model docelowego rekordu, np. 'BadgeVersion', 'TouristProfile'.",
                        max_length=60,
                        verbose_name="Typ obiektu",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        help_text="Wartość klucza głównego lub kod obiektu (dla składanych kluczy).",
                        max_length=100,
                        verbose_name="ID obiektu",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Dane zdarzenia w formacie JSON — np. {badge_code, version_code, new_status, reason}.",
                        verbose_name="Dane zdarzenia (payload)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Czas zdarzenia (UTC)"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs_caused",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktor (User)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Audytowy",
                "verbose_name_plural": "Logi Audytowe",
                "db_table": "audit_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
