# Generated by Django 6.0.8 on 2026-09-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourists", "0004_alter_ascentlog_souvenir_image_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="ascentlog",
            name="is_rejected",
            field=models.BooleanField(
                default=False,
                help_text="AUDYT-089 (Invariant S-04): wejście odrzucone (np. błąd weryfikacji) nie jest brane pod uwagę przy weryfikacji odznak. Nie jest usuwane — chroni historię.",
                verbose_name="Odrzucony (Czarna Lista)",
            ),
        ),
    ]
