"""Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ZASADA BEZSTANOWYCH TESTÓW: Używamy zaślepki, jeśli brak zmiennej środowiskowej
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-dummy-key-for-local-tests-only")

# W trybie testowym/lokalnym DEBUG jest domyślnie True
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# Fail-Fast: Blokujemy start aplikacji TYLKO na produkcji, jeśli ktoś zapomniał klucza!
if not DEBUG and SECRET_KEY == "django-insecure-dummy-key-for-local-tests-only":
    raise ValueError("DJANGO_SECRET_KEY environment variable must be set in production.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django_jsonform",
    "django_celery_beat",
    "leaflet",
    "tinymce",
    "apps.badges",
    "apps.tourists",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "badges_system_db",  # Nazwa Twojej bazy danych
        "USER": "postgres",
        "PASSWORD": "password",  # Twoje hasło do bazy
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# Ustawienie wymagane przez serwery OpenStreetMap (Tile Usage Policy)
# Pozwala przeglądarce wysłać nagłówek Referer do obcych serwerów (jak OSM),
# co odblokowuje kafelki map w Django Adminie.
SECURE_REFERRER_POLICY = "origin-when-cross-origin"


# ===============================
# CELERY & REDIS CONFIGURATION
# ===============================
# Adres brokera (kolejki zadań), do którego Django wysyła polecenia
CELERY_BROKER_URL = "redis://localhost:6379/0"
# Adres, pod którym Celery zapisuje wyniki zadań (opcjonalnie, ale przydatne)
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
# Format serializacji danych (JSON jest bezpieczny i uniwersalny)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
# Strefa czasowa dla zadań opóźnionych
CELERY_TIMEZONE = "Europe/Warsaw"
# Mówimy Celery, by harmonogramy brało z bazy danych (Django Admin), a nie z kodu!
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


TINYMCE_DEFAULT_CONFIG = {
    "height": "500px",
    "width": "100%",
    "menubar": True,
    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount",
    "toolbar": "undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help",
}


# ==========================================
# DJANGO UNFOLD (Modern Admin Theme)
# ==========================================
UNFOLD = {
    "SITE_TITLE": "Badges Admin",
    "SITE_HEADER": "System Odznak Turystycznych",
    "SITE_URL": "/",
    "COLORS": {
        "primary": {
            "50": "#f0f9ff",
            "100": "#e0f2fe",
            "200": "#bae6fd",
            "300": "#7dd3fc",
            "400": "#38bdf8",
            "500": "#0ea5e9",
            "600": "#0284c7",
            "700": "#0369a1",
            "800": "#075985",
            "900": "#0c4a6e",
        },
    },
}
