"""Początkowa migracja dla aplikacji odznak."""

# Generated by Django 6.0.3 on 2026-07-04 08:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_jsonform.models.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    """Klasa migracji początkowej."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizerModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nazwa organizatora")),
                ("contact_info", models.TextField(blank=True, verbose_name="Dane kontaktowe")),
                ("club_rules_link", models.URLField(blank=True, max_length=500, verbose_name="Regulamin klubu (Link)")),
                (
                    "club_badge_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizers/badges/", verbose_name="Odznaka klubowa"
                    ),
                ),
                (
                    "is_booklet_required",
                    models.BooleanField(
                        default=False,
                        help_text="Zaznacz, jeśli organizator bezwzględnie wymaga posiadania swojej książeczki do zdobywania jego odznak.",
                        verbose_name="Wymagana książeczka klubowa",
                    ),
                ),
                (
                    "booklet_template_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="organizers/booklets/", verbose_name="Wzór książeczki (PDF)"
                    ),
                ),
                (
                    "has_publication_consent",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Zaznacz, jeśli masz zgodę organizatora na publikację wizerunku odznak, książeczek i treści regulaminów.",
                        ),
                        verbose_name="Zgoda na publikację",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organizator",
                "verbose_name_plural": "Organizatorzy",
                "db_table": "odznaki_organizer",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BadgeNewsItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("change_date_str", models.CharField(max_length=50, verbose_name="Data z portalu")),
                (
                    "change_type",
                    models.CharField(
                        choices=[("ADDITION", "Nowa odznaka"), ("CHANGE", "Zmiana regulaminu")],
                        max_length=20,
                        verbose_name="Typ zmiany",
                    ),
                ),
                ("badge_name", models.CharField(max_length=255, verbose_name="Nazwa odznaki")),
                ("source_url", models.URLField(max_length=500, verbose_name="Źródło (Link)")),
                ("is_read", models.BooleanField(default=False, verbose_name="Przeczytane")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Aktualność Odznaki",
                "verbose_name_plural": "Radar Aktualności",
                "db_table": "odznaki_badge_news_item",
                "ordering": ["-created_at"],
                "unique_together": {("change_date_str", "change_type", "badge_name")},
            },
        ),
        migrations.CreateModel(
            name="CountryModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(default=0)),
                ("neighbors", models.ManyToManyField(blank=True, to="badges.countrymodel", verbose_name="Sąsiedzi")),
            ],
            options={
                "verbose_name": "Państwo",
                "verbose_name_plural": "Państwa",
                "db_table": "odznaki_country",
            },
        ),
        migrations.CreateModel(
            name="MacroregionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "neighbors",
                    models.ManyToManyField(blank=True, to="badges.macroregionmodel", verbose_name="Sąsiedzi"),
                ),
            ],
            options={
                "verbose_name": "Makroregion",
                "verbose_name_plural": "Makroregiony",
                "db_table": "odznaki_macroregion",
            },
        ),
        migrations.CreateModel(
            name="MesoregionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "macroregion",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="badges.macroregionmodel"
                    ),
                ),
                ("neighbors", models.ManyToManyField(blank=True, to="badges.mesoregionmodel", verbose_name="Sąsiedzi")),
            ],
            options={
                "verbose_name": "Mezoregion",
                "verbose_name_plural": "Mezoregiony",
                "db_table": "odznaki_mesoregion",
            },
        ),
        migrations.CreateModel(
            name="BadgeModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Kod")),
                ("name", models.CharField(max_length=255, verbose_name="Nazwa Odznaki")),
                ("established_date", models.DateField(blank=True, null=True, verbose_name="Data ustanowienia")),
                (
                    "is_booklet_required",
                    models.BooleanField(
                        default=False,
                        help_text="Zaznacz, jeśli ta konkretna odznaka wymaga posiadania dedykowanej książeczki do odznaki.",
                        verbose_name="Wymagana książeczka odznaki",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="badges.organizermodel",
                        verbose_name="Organizator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odznaka",
                "verbose_name_plural": "Odznaki",
                "db_table": "odznaki_badge",
            },
        ),
        migrations.CreateModel(
            name="OsmTypeMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("osm_key", models.CharField(max_length=100, verbose_name="Klucz OSM (np. natural)")),
                ("osm_value", models.CharField(max_length=100, verbose_name="Wartość OSM (np. peak)")),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Wpisz np. 'Szczyt', 'Wodospad'. Zostaw puste, jeśli oczekuje na decyzję.",
                        max_length=100,
                        null=True,
                        verbose_name="Typ docelowy",
                    ),
                ),
                (
                    "is_ignored",
                    models.BooleanField(
                        default=False,
                        help_text="Zaznacz, jeśli ten tag to śmieć (np. tablica informacyjna) i system ma go nigdy nie używać.",
                        verbose_name="Ignoruj",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapowanie Typu OSM",
                "verbose_name_plural": "Słownik Mapowań OSM",
                "db_table": "odznaki_osm_type_mapping",
                "ordering": ["is_ignored", "target_type", "osm_key"],
                "unique_together": {("osm_key", "osm_value")},
            },
        ),
        migrations.CreateModel(
            name="ProvinceModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="badges.countrymodel")),
                ("neighbors", models.ManyToManyField(blank=True, to="badges.provincemodel", verbose_name="Sąsiedzi")),
            ],
            options={
                "verbose_name": "Prowincja",
                "verbose_name_plural": "Prowincje",
                "db_table": "odznaki_province",
                "unique_together": {("country", "code")},
            },
        ),
        migrations.CreateModel(
            name="SubprovinceModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "neighbors",
                    models.ManyToManyField(blank=True, to="badges.subprovincemodel", verbose_name="Sąsiedzi"),
                ),
                ("province", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="badges.provincemodel")),
            ],
            options={
                "verbose_name": "Podprowincja",
                "verbose_name_plural": "Podprowincje",
                "db_table": "odznaki_subprovince",
                "unique_together": {("province", "code")},
            },
        ),
        migrations.AddField(
            model_name="macroregionmodel",
            name="subprovince",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="badges.subprovincemodel"
            ),
        ),
        migrations.CreateModel(
            name="TouristObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=200, null=True, verbose_name="Główna nazwa")),
                (
                    "alt_name",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Alternatywna nazwa"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, unique=True, verbose_name="Unikalny kod (Ewidencja)"
                    ),
                ),
                ("type", models.CharField(default="Szczyt", max_length=100, verbose_name="Typ obiektu")),
                (
                    "altitude",
                    models.IntegerField(
                        blank=True, help_text="W m n.p.m. (Wymagane dla Szczytów)", null=True, verbose_name="Wysokość"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Współrzędne (GPS)"
                    ),
                ),
                (
                    "wikipedia_link",
                    models.URLField(
                        blank=True,
                        help_text="Opcjonalny. Jeśli nie podano, system spróbuje wyciągnąć go asynchronicznie z tagów OSM (np. wikipedia:pl).",
                        max_length=500,
                        null=True,
                        verbose_name="Link do Wikipedii",
                    ),
                ),
                ("local_names", models.JSONField(blank=True, default=dict, verbose_name="Lokalne nazwy i graniczne")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Odznacz to (Soft Delete), jeśli wieża spłonęła lub schronisko zostało rozebrane. Nie usuwaj obiektu z bazy, by nie popsuć historii zdobytych odznak!",
                        verbose_name="Czy istnieje fizycznie?",
                    ),
                ),
                (
                    "existence_start",
                    models.DateField(
                        blank=True,
                        help_text="Wypełnij np. dla nowo wybudowanych wież widokowych. Puste = istniał 'od zawsze' (np. góry).",
                        null=True,
                        verbose_name="Data powstania/otwarcia",
                    ),
                ),
                (
                    "existence_end",
                    models.DateField(
                        blank=True,
                        help_text="Wypełnij dla obiektów rozebranych lub zniszczonych. Puste = istnieje do dziś.",
                        null=True,
                        verbose_name="Data zniszczenia/zamknięcia",
                    ),
                ),
                (
                    "osm_id",
                    models.CharField(
                        blank=True,
                        help_text="Format: node/123, way/456, relation/789",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="OSM ID",
                    ),
                ),
                ("osm_version", models.IntegerField(blank=True, help_text="Wersja edycji w OSM", null=True)),
                ("osm_timestamp", models.DateTimeField(blank=True, help_text="Data ostatniej edycji w OSM", null=True)),
                (
                    "osm_raw_tags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Wszystkie pobrane tagi z OSM (Data Lake).",
                        verbose_name="Surowe tagi OSM",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Szkic"),
                            ("FETCHING_OSM", "Pobieranie z OSM..."),
                            ("READY", "Gotowy (Przeliczony)"),
                            ("ERROR", "Błąd pobierania"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "osm_error",
                    models.TextField(
                        blank=True,
                        help_text="Jeśli Celery napotka krytyczny błąd (np. obiekt nie istnieje), tu pojawi się przyczyna.",
                        null=True,
                        verbose_name="Błąd asynchronicznego pobierania",
                    ),
                ),
                (
                    "last_sync_check",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data ostatniego sprawdzenia obiektu przez asynchronicznego stróża.",
                        null=True,
                        verbose_name="Ostatnia weryfikacja w OSM",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_object",
                    models.ForeignKey(
                        blank=True,
                        help_text="Np. Szczyt, na którym znajduje się to schronisko.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_objects",
                        to="badges.touristobject",
                        verbose_name="Obiekt nadrzędny",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obiekt Turystyczny",
                "verbose_name_plural": "Obiekty Turystyczne",
                "db_table": "odznaki_tourist_object",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OsmSyncConflict",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("field_name", models.CharField(max_length=50, verbose_name="Zmienione pole")),
                ("old_value", models.CharField(blank=True, max_length=500, null=True, verbose_name="Wartość w bazie")),
                ("new_value", models.CharField(blank=True, max_length=500, null=True, verbose_name="Propozycja z OSM")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Oczekujące na decyzję"),
                            ("ACCEPTED", "Zaakceptowane (Nadpisane)"),
                            ("REJECTED", "Odrzucone (Zachowano stare)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tourist_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_conflicts",
                        to="badges.touristobject",
                        verbose_name="Obiekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konflikt Danych OSM",
                "verbose_name_plural": "Konflikty Danych OSM",
                "db_table": "odznaki_osm_sync_conflict",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BadgeVersionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_code", models.CharField(max_length=50, verbose_name="Wersja (np. v2024)")),
                ("valid_from", models.DateField(verbose_name="Obowiązuje od")),
                (
                    "official_link",
                    models.URLField(blank=True, max_length=500, verbose_name="Oficjalny link (Źródło organizatora)"),
                ),
                ("rules_link", models.URLField(blank=True, max_length=500, verbose_name="Link do archiwum regulaminu")),
                (
                    "system_entry_date",
                    models.DateField(auto_now_add=True, verbose_name="Data wprowadzenia archiwum do systemu"),
                ),
                (
                    "booklet_template_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="badges/versions/booklets/", verbose_name="Wzór książeczki"
                    ),
                ),
                (
                    "rules_text",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Wklej tutaj oryginalną treść regulaminu PTTK dla zachowania historii.",
                        null=True,
                        verbose_name="Treść regulaminu",
                    ),
                ),
                (
                    "rules",
                    django_jsonform.models.fields.JSONField(
                        blank=True, default=list, null=True, verbose_name="Reguły biznesowe"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="badges.badgemodel",
                        verbose_name="Odznaka",
                    ),
                ),
                (
                    "pool_peaks",
                    models.ManyToManyField(blank=True, to="badges.touristobject", verbose_name="Pula Obiektów"),
                ),
            ],
            options={
                "verbose_name": "Wersja Regulaminu",
                "verbose_name_plural": "Wersje Regulaminów",
                "db_table": "odznaki_badge_version",
            },
        ),
        migrations.CreateModel(
            name="TouristRegionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "macroregions",
                    models.ManyToManyField(blank=True, to="badges.macroregionmodel", verbose_name="Makroregiony"),
                ),
                (
                    "mesoregions",
                    models.ManyToManyField(blank=True, to="badges.mesoregionmodel", verbose_name="Mezoregiony"),
                ),
                ("provinces", models.ManyToManyField(blank=True, to="badges.provincemodel", verbose_name="Prowincje")),
                (
                    "subprovinces",
                    models.ManyToManyField(blank=True, to="badges.subprovincemodel", verbose_name="Podprowincje"),
                ),
            ],
            options={
                "verbose_name": "Region Turystyczny",
                "verbose_name_plural": "Regiony Turystyczne",
                "db_table": "odznaki_tourist_region",
            },
        ),
        migrations.CreateModel(
            name="BadgeTierModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("jednostopniowa", "Jednostopniowa"),
                            ("popularna", "Popularna"),
                            ("brazowa", "Brązowa"),
                            ("srebrna", "Srebrna"),
                            ("zlota", "Złota"),
                            ("platynowa", "Platynowa"),
                            ("diamentowa", "Diamentowa"),
                            ("brylantowa", "Brylantowa"),
                            ("mala", "Mała"),
                            ("duza", "Duża"),
                            ("wielka", "Wielka"),
                            ("podstawowa", "Podstawowa"),
                            ("glowna", "Główna"),
                            ("mala_popularna", "Mała popularna"),
                            ("mala_brazowa", "Mała brązowa"),
                            ("za_wytrwalosc", "Za Wytrwałość"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Stopień",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Kolejność zdobywania (1=najniższy)",
                        verbose_name="Kolejność zdobywania (1=najniższy)",
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="badges/tiers/", verbose_name="Zdjęcie blachy (Odznaki)"
                    ),
                ),
                (
                    "required_peaks_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Puste = wymaga zdobycia WSZYSTKIECH szczytów z puli tej wersji.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="badges.badgeversionmodel",
                        verbose_name="Wersja odznaki",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stopień Odznaki",
                "verbose_name_plural": "Stopnie Odznak",
                "db_table": "odznaki_badge_tier",
                "ordering": ["version", "order"],
                "constraints": [
                    models.UniqueConstraint(fields=("version", "name"), name="unique_tier_name_per_version"),
                    models.UniqueConstraint(fields=("version", "order"), name="unique_tier_order_per_version"),
                ],
                "unique_together": {("version", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProximityCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("distance_meters", models.FloatField(verbose_name="Odległość [m]")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Oczekujące na decyzję"),
                            ("RESOLVED", "Rozwiązane (Połączone)"),
                            ("IGNORED", "Ignorowane"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "obj_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proximity_a",
                        to="badges.touristobject",
                    ),
                ),
                (
                    "obj_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proximity_b",
                        to="badges.touristobject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kandydat do Klastrowania (Radar)",
                "verbose_name_plural": "Radar Klastrowania",
                "db_table": "odznaki_proximity_candidate",
                "ordering": ["-created_at"],
                "unique_together": {("obj_a", "obj_b")},
            },
        ),
        migrations.CreateModel(
            name="ObjectRegionCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "region_level",
                    models.CharField(
                        choices=[
                            ("COUNTRY", "Państwo"),
                            ("VOIVODESHIP", "Województwo"),
                            ("PROVINCE", "Prowincja"),
                            ("SUBPROVINCE", "Podprowincja"),
                            ("MACROREGION", "Makroregion"),
                            ("MESOREGION", "Mezoregion"),
                            ("TOURIST_REGION", "Region Turystyczny"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "region_id",
                    models.BigIntegerField(help_text="ID wiersza z tabeli odpowiadającej poziomowi region_level."),
                ),
                (
                    "region_name",
                    models.CharField(
                        help_text="Zdenormalizowana nazwa regionu do błyskawicznego wyświetlania (np. w panelu).",
                        max_length=100,
                    ),
                ),
                (
                    "distance_meters",
                    models.FloatField(
                        default=0.0, help_text="Odległość od krawędzi regionu w metrach (0.0 = wewnątrz)."
                    ),
                ),
                (
                    "tourist_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_regions",
                        to="badges.touristobject",
                    ),
                ),
            ],
            options={
                "db_table": "odznaki_object_region_cache",
                "indexes": [
                    models.Index(fields=["tourist_object", "region_level"], name="odznaki_obj_tourist_c6c6f9_idx"),
                    models.Index(fields=["region_level", "region_id"], name="odznaki_obj_region__f5a923_idx"),
                ],
                "unique_together": {("tourist_object", "region_level", "region_id")},
            },
        ),
        migrations.CreateModel(
            name="VoivodeshipModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="badges.countrymodel")),
                (
                    "neighbors",
                    models.ManyToManyField(blank=True, to="badges.voivodeshipmodel", verbose_name="Sąsiedzi"),
                ),
            ],
            options={
                "verbose_name": "Województwo",
                "verbose_name_plural": "Województwa",
                "db_table": "odznaki_voivodeship",
                "unique_together": {("country", "code"), ("country", "name")},
            },
        ),
    ]
