# Generated by Django 6.0.3 on 2026-04-09 22:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountryModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Państwo",
                "verbose_name_plural": "Państwa",
                "db_table": "odznaki_country",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MacroregionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Makroregion",
                "verbose_name_plural": "Makroregiony",
                "db_table": "odznaki_macroregion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MesoregionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mezoregion",
                "verbose_name_plural": "Mezoregiony",
                "db_table": "odznaki_mesoregion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProvinceModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prowincja",
                "verbose_name_plural": "Prowincje",
                "db_table": "odznaki_province",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubprovinceModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Podprowincja",
                "verbose_name_plural": "Podprowincje",
                "db_table": "odznaki_subprovince",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VoivodeshipModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Województwo",
                "verbose_name_plural": "Województwa",
                "db_table": "odznaki_voivodeship",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizerModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nazwa organizatora")),
                ("contact_info", models.TextField(blank=True, verbose_name="Dane kontaktowe")),
                ("club_rules_link", models.URLField(blank=True, max_length=500, verbose_name="Regulamin klubu (Link)")),
                (
                    "club_badge_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizers/badges/", verbose_name="Odznaka klubowa"
                    ),
                ),
                (
                    "booklet_template_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="organizers/booklets/", verbose_name="Wzór książeczki (PDF)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organizator",
                "verbose_name_plural": "Organizatorzy",
                "db_table": "odznaki_organizer",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BadgeModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Kod")),
                ("name", models.CharField(max_length=255, verbose_name="Nazwa Odznaki")),
                ("established_date", models.DateField(blank=True, null=True, verbose_name="Data ustanowienia")),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="badges.organizermodel",
                        verbose_name="Organizator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odznaka",
                "verbose_name_plural": "Odznaki",
                "db_table": "odznaki_badge",
            },
        ),
        migrations.CreateModel(
            name="TouristObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=200, null=True, verbose_name="Główna nazwa")),
                (
                    "alt_name",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Alternatywna nazwa"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, unique=True, verbose_name="Unikalny kod (Ewidencja)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PEAK", "Szczyt"),
                            ("HUT", "Schronisko"),
                            ("CAVE", "Jaskinia"),
                            ("CASTLE", "Zamek / Ruiny"),
                            ("LIGHTHOUSE", "Latarnia Morska"),
                            ("OTHER", "Inny punkt (POI)"),
                        ],
                        default="PEAK",
                        max_length=20,
                        verbose_name="Typ obiektu",
                    ),
                ),
                (
                    "altitude",
                    models.IntegerField(
                        blank=True, help_text="W m n.p.m. (Wymagane dla Szczytów)", null=True, verbose_name="Wysokość"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Współrzędne (GPS)"
                    ),
                ),
                (
                    "wikipedia_link",
                    models.URLField(
                        blank=True,
                        help_text="Opcjonalny. Jeśli nie podano, system spróbuje wyciągnąć go asynchronicznie z tagów OSM (np. wikipedia:pl).",
                        max_length=500,
                        null=True,
                        verbose_name="Link do Wikipedii",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Czy istnieje fizycznie?")),
                (
                    "osm_id",
                    models.CharField(
                        blank=True,
                        help_text="Format: node/123, way/456, relation/789",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="OSM ID",
                    ),
                ),
                (
                    "osm_raw_tags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Wszystkie pobrane tagi z OSM (Data Lake).",
                        verbose_name="Surowe tagi OSM",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_object",
                    models.ForeignKey(
                        blank=True,
                        help_text="Np. Szczyt, na którym znajduje się to schronisko.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_objects",
                        to="badges.touristobject",
                        verbose_name="Obiekt nadrzędny",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obiekt Turystyczny",
                "verbose_name_plural": "Obiekty Turystyczne",
                "db_table": "odznaki_tourist_object",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BadgeVersionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_code", models.CharField(max_length=50, verbose_name="Wersja (np. v2024)")),
                ("valid_from", models.DateField(verbose_name="Obowiązuje od")),
                (
                    "official_link",
                    models.URLField(blank=True, max_length=500, verbose_name="Oficjalny link (Źródło organizatora)"),
                ),
                ("rules_link", models.URLField(blank=True, max_length=500, verbose_name="Link do archiwum regulaminu")),
                (
                    "system_entry_date",
                    models.DateField(auto_now_add=True, verbose_name="Data wprowadzenia archiwum do systemu"),
                ),
                (
                    "booklet_template_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="badges/versions/booklets/", verbose_name="Wzór książeczki"
                    ),
                ),
                ("rules", django_jsonform.models.fields.JSONField(default=list, verbose_name="Reguły biznesowe")),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="badges.badgemodel",
                        verbose_name="Odznaka",
                    ),
                ),
                (
                    "pool_peaks",
                    models.ManyToManyField(blank=True, to="badges.touristobject", verbose_name="Pula Obiektów"),
                ),
            ],
            options={
                "verbose_name": "Wersja Regulaminu",
                "verbose_name_plural": "Wersje Regulaminów",
                "db_table": "odznaki_badge_version",
            },
        ),
        migrations.CreateModel(
            name="TouristRegionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "macroregions",
                    models.ManyToManyField(blank=True, to="badges.macroregionmodel", verbose_name="Makroregiony"),
                ),
                (
                    "mesoregions",
                    models.ManyToManyField(blank=True, to="badges.mesoregionmodel", verbose_name="Mezoregiony"),
                ),
                ("provinces", models.ManyToManyField(blank=True, to="badges.provincemodel", verbose_name="Prowincje")),
                (
                    "subprovinces",
                    models.ManyToManyField(blank=True, to="badges.subprovincemodel", verbose_name="Podprowincje"),
                ),
            ],
            options={
                "verbose_name": "Region Turystyczny",
                "verbose_name_plural": "Regiony Turystyczne",
                "db_table": "odznaki_tourist_region",
            },
        ),
        migrations.CreateModel(
            name="BadgeTierModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("jednostopniowa", "Jednostopniowa"),
                            ("popularna", "Popularna"),
                            ("brazowa", "Brązowa"),
                            ("srebrna", "Srebrna"),
                            ("zlota", "Złota"),
                            ("platynowa", "Platynowa"),
                            ("diamentowa", "Diamentowa"),
                            ("brylantowa", "Brylantowa"),
                            ("mala", "Mała"),
                            ("duza", "Duża"),
                            ("wielka", "Wielka"),
                            ("podstawowa", "Podstawowa"),
                            ("glowna", "Główna"),
                            ("mala_popularna", "Mała popularna"),
                            ("mala_brazowa", "Mała brązowa"),
                            ("za_wytrwalosc", "Za Wytrwałość"),
                        ],
                        default="jednostopniowa",
                        max_length=50,
                        verbose_name="Stopień",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Kolejność zdobywania (1=najniższy)",
                        verbose_name="Kolejność zdobywania (1=najniższy)",
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="badges/tiers/", verbose_name="Zdjęcie blachy (Odznaki)"
                    ),
                ),
                (
                    "required_peaks_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Puste = wymaga zdobycia WSZYSTKIECH szczytów z puli tej wersji.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="badges.badgeversionmodel",
                        verbose_name="Wersja odznaki",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stopień Odznaki",
                "verbose_name_plural": "Stopnie Odznak",
                "db_table": "odznaki_badge_tier",
                "ordering": ["version", "order"],
                "unique_together": {("version", "name")},
            },
        ),
        migrations.CreateModel(
            name="ObjectRegionCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "region_level",
                    models.CharField(
                        choices=[
                            ("COUNTRY", "Państwo"),
                            ("VOIVODESHIP", "Województwo"),
                            ("PROVINCE", "Prowincja"),
                            ("SUBPROVINCE", "Podprowincja"),
                            ("MACROREGION", "Makroregion"),
                            ("MESOREGION", "Mezoregion"),
                            ("TOURIST_REGION", "Region Turystyczny"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "region_id",
                    models.BigIntegerField(help_text="ID wiersza z tabeli odpowiadającej poziomowi region_level."),
                ),
                (
                    "region_name",
                    models.CharField(
                        help_text="Zdenormalizowana nazwa regionu do błyskawicznego wyświetlania (np. w panelu).",
                        max_length=100,
                    ),
                ),
                (
                    "distance_meters",
                    models.FloatField(
                        default=0.0, help_text="Odległość od krawędzi regionu w metrach (0.0 = wewnątrz)."
                    ),
                ),
                (
                    "tourist_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_regions",
                        to="badges.touristobject",
                    ),
                ),
            ],
            options={
                "db_table": "odznaki_object_region_cache",
                "indexes": [
                    models.Index(fields=["tourist_object", "region_level"], name="odznaki_obj_tourist_c6c6f9_idx"),
                    models.Index(fields=["region_level", "region_id"], name="odznaki_obj_region__f5a923_idx"),
                ],
                "unique_together": {("tourist_object", "region_level", "region_id")},
            },
        ),
    ]
