# Generated by Django 6.0.8 on 2026-08-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizermodel",
            name="has_publication_consent",
            field=models.BooleanField(
                default=False,
                help_text="Zaznacz, jeśli masz zgodę organizatora na publikację wizerunku odznak, książeczek i treści regulaminów.",
                verbose_name="Zgoda na publikację",
            ),
        ),
        migrations.AddIndex(
            model_name="touristobject",
            index=models.Index(fields=["name"], name="tourist_object_name_idx"),
        ),
        migrations.AddIndex(
            model_name="touristobject",
            index=models.Index(fields=["status"], name="tourist_object_status_idx"),
        ),
        migrations.AddIndex(
            model_name="touristobject",
            index=models.Index(fields=["is_active"], name="tourist_object_is_active_idx"),
        ),
    ]
