# Generated by Django 6.0.3 on 2026-04-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristobject",
            name="type",
            field=models.CharField(default="Szczyt", max_length=100, verbose_name="Typ obiektu"),
        ),
    ]
