# Generated by Django 6.0.3 on 2026-04-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0002_alter_touristobject_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OsmTypeMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("osm_key", models.CharField(max_length=100, verbose_name="Klucz OSM (np. natural)")),
                ("osm_value", models.CharField(max_length=100, verbose_name="Wartość OSM (np. peak)")),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Wpisz np. 'Szczyt', 'Wodospad'. Zostaw puste, jeśli oczekuje na decyzję.",
                        max_length=100,
                        null=True,
                        verbose_name="Typ docelowy",
                    ),
                ),
                (
                    "is_ignored",
                    models.BooleanField(
                        default=False,
                        help_text="Zaznacz, jeśli ten tag to śmieć (np. tablica informacyjna) i system ma go nigdy nie używać.",
                        verbose_name="Ignoruj",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapowanie Typu OSM",
                "verbose_name_plural": "Słownik Mapowań OSM",
                "db_table": "odznaki_osm_type_mapping",
                "ordering": ["is_ignored", "target_type", "osm_key"],
                "unique_together": {("osm_key", "osm_value")},
            },
        ),
        migrations.CreateModel(
            name="PeakModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa szczytu")),
                ("altitude", models.IntegerField(verbose_name="Wysokość (m n.p.m.)")),
                ("link", models.URLField(blank=True, max_length=255, null=True, verbose_name="Link do opisu")),
                ("shape", models.CharField(blank=True, max_length=255, null=True, verbose_name="Kształt szczytu")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano")),
                (
                    "mesoregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peaks",
                        to="badges.mesoregionmodel",
                        verbose_name="Mezoregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Szczyt",
                "verbose_name_plural": "Szczyty",
                "db_table": "odznaki_peak",
            },
        ),
    ]
