# Generated by Django 6.0.8 on 2026-09-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0002_alter_organizermodel_has_publication_consent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristobject",
            name="existence_end",
            field=models.DateField(
                blank=True,
                help_text="Wypełnij dla obiektów rozebranych lub zniszczonych. Pusty = istnieje do dziś.",
                null=True,
                verbose_name="Data zniszczenia/zamknięcia",
            ),
        ),
        migrations.AlterField(
            model_name="touristobject",
            name="existence_start",
            field=models.DateField(
                blank=True,
                help_text="Wypełnij np. dla nowo wybudowanych wież widokowych. Pusty = istniał 'od zawsze' (np. góry).",
                null=True,
                verbose_name="Data powstania/otwarcia",
            ),
        ),
    ]
