# Generated by Django 6.0.3 on 2026-04-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0003_osmtypemapping_peakmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristobject",
            name="local_names",
            field=models.JSONField(blank=True, default=dict, verbose_name="Lokalne nazwy i graniczne"),
        ),
        migrations.AddField(
            model_name="touristobject",
            name="osm_timestamp",
            field=models.DateTimeField(blank=True, help_text="Data ostatniej edycji w OSM", null=True),
        ),
        migrations.AddField(
            model_name="touristobject",
            name="osm_version",
            field=models.IntegerField(blank=True, help_text="Wersja edycji w OSM", null=True),
        ),
    ]
