# Generated by Django 6.0.8 on 2026-09-07 15:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models

import apps.badges.models.region


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0003_alter_touristobject_existence_end_and_more"),
    ]

    operations = [
        CreateExtension(name="ltree"),
        migrations.CreateModel(
            name="RegionFlatModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("translation", models.CharField(blank=True, max_length=100, verbose_name="Tłumaczenie")),
                ("code", models.CharField(max_length=10, verbose_name="Kod")),
                ("link", models.CharField(blank=True, max_length=200, verbose_name="Link (Wiki)")),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Kształt"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("COUNTRY", "Państwo"),
                            ("VOIVODESHIP", "Województwo"),
                            ("PROVINCE", "Prowincja"),
                            ("SUBPROVINCE", "Podprowincja"),
                            ("MACROREGION", "Makroregion"),
                            ("MESOREGION", "Mezoregion"),
                            ("TOURIST_REGION", "Region Turystyczny"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", apps.badges.models.region.LtreeField(db_index=True, verbose_name="Ścieżka ltree")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("neighbors", models.ManyToManyField(blank=True, to="badges.regionflatmodel", verbose_name="Sąsiedzi")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="badges.regionflatmodel",
                        verbose_name="Rodzic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region (Flat)",
                "verbose_name_plural": "Regiony (Flat)",
                "db_table": "regions_flat",
                "constraints": [models.UniqueConstraint(fields=("level", "code"), name="uq_regions_flat_level_code")],
            },
        ),
    ]
