# Generated by Django 6.0.3 on 2026-04-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0004_touristobject_local_names_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristobject",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Odznacz to (Soft Delete), jeśli wieża spłonęła lub schronisko zostało rozebrane. Nie usuwaj obiektu z bazy, by nie popsuć historii zdobytych odznak!",
                verbose_name="Czy istnieje fizycznie?",
            ),
        ),
    ]
