# Generated by Django 6.0.3 on 2026-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0005_alter_touristobject_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgetiermodel",
            name="name",
            field=models.CharField(
                choices=[
                    ("jednostopniowa", "Jednostopniowa"),
                    ("popularna", "Popularna"),
                    ("brazowa", "Brązowa"),
                    ("srebrna", "Srebrna"),
                    ("zlota", "Złota"),
                    ("platynowa", "Platynowa"),
                    ("diamentowa", "Diamentowa"),
                    ("brylantowa", "Brylantowa"),
                    ("mala", "Mała"),
                    ("duza", "Duża"),
                    ("wielka", "Wielka"),
                    ("podstawowa", "Podstawowa"),
                    ("glowna", "Główna"),
                    ("mala_popularna", "Mała popularna"),
                    ("mala_brazowa", "Mała brązowa"),
                    ("za_wytrwalosc", "Za Wytrwałość"),
                ],
                max_length=50,
                null=True,
                verbose_name="Stopień",
            ),
        ),
    ]
