# Generated by Django 6.0.3 on 2026-04-16 19:11

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0006_alter_badgetiermodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeversionmodel",
            name="rules_text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Wklej tutaj oryginalną treść regulaminu PTTK dla zachowania historii.",
                null=True,
                verbose_name="Treść regulaminu",
            ),
        ),
        migrations.AddField(
            model_name="organizermodel",
            name="has_publication_consent",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Zaznacz, jeśli masz zgodę organizatora na publikację wizerunku odznak, książeczek i treści regulaminów.",
                ),
                verbose_name="Zgoda na publikację",
            ),
        ),
    ]
