# Generated by Django 6.0.3 on 2026-04-21 08:51

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0007_badgeversionmodel_rules_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgeversionmodel",
            name="rules",
            field=django_jsonform.models.fields.JSONField(
                blank=True, default=list, null=True, verbose_name="Reguły biznesowe"
            ),
        ),
    ]
