# Generated by Django 6.0.3 on 2026-04-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0008_alter_badgeversionmodel_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgemodel",
            name="is_booklet_required",
            field=models.BooleanField(
                default=False,
                help_text="Zaznacz, jeśli ta konkretna odznaka wymaga posiadania dedykowanej książeczki do odznaki.",
                verbose_name="Wymagana książeczka odznaki",
            ),
        ),
        migrations.AddField(
            model_name="organizermodel",
            name="is_booklet_required",
            field=models.BooleanField(
                default=False,
                help_text="Zaznacz, jeśli organizator bezwzględnie wymaga posiadania swojej książeczki do zdobywania jego odznak.",
                verbose_name="Wymagana książeczka klubowa",
            ),
        ),
    ]
