# Generated by Django 6.0.3 on 2026-04-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0009_badgemodel_is_booklet_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristobject",
            name="existence_end",
            field=models.DateField(
                blank=True,
                help_text="Wypełnij dla obiektów rozebranych lub zniszczonych. Puste = istnieje do dziś.",
                null=True,
                verbose_name="Data zniszczenia/zamknięcia",
            ),
        ),
        migrations.AddField(
            model_name="touristobject",
            name="existence_start",
            field=models.DateField(
                blank=True,
                help_text="Wypełnij np. dla nowo wybudowanych wież widokowych. Puste = istniał 'od zawsze' (np. góry).",
                null=True,
                verbose_name="Data powstania/otwarcia",
            ),
        ),
    ]
