# Generated by Django 6.0.3 on 2026-04-23 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0010_touristobject_existence_end_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PeakModel",
        ),
    ]
