# Generated by Django 6.0.3 on 2026-04-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0011_delete_peakmodel"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="badgetiermodel",
            constraint=models.UniqueConstraint(fields=("version", "name"), name="unique_tier_name_per_version"),
        ),
        migrations.AddConstraint(
            model_name="badgetiermodel",
            constraint=models.UniqueConstraint(fields=("version", "order"), name="unique_tier_order_per_version"),
        ),
    ]
