# Generated by Django 6.0.3 on 2026-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0012_badgetiermodel_unique_tier_name_per_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristobject",
            name="osm_error",
            field=models.TextField(
                blank=True,
                help_text="Jeśli Celery napotka krytyczny błąd (np. obiekt nie istnieje), tu pojawi się przyczyna.",
                null=True,
                verbose_name="Błąd asynchronicznego pobierania",
            ),
        ),
        migrations.AddField(
            model_name="touristobject",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Szkic"),
                    ("FETCHING_OSM", "Pobieranie z OSM..."),
                    ("READY", "Gotowy (Przeliczony)"),
                    ("ERROR", "Błąd pobierania"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
