# Generated by Django 6.0.3 on 2026-05-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0013_touristobject_osm_error_touristobject_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProximityCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("distance_meters", models.FloatField(verbose_name="Odległość [m]")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Oczekujące na decyzję"),
                            ("RESOLVED", "Rozwiązane (Połączone)"),
                            ("IGNORED", "Ignorowane"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "obj_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proximity_a",
                        to="badges.touristobject",
                    ),
                ),
                (
                    "obj_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proximity_b",
                        to="badges.touristobject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kandydat do Klastrowania (Radar)",
                "verbose_name_plural": "Radar Klastrowania",
                "db_table": "odznaki_proximity_candidate",
                "ordering": ["-created_at"],
                "unique_together": {("obj_a", "obj_b")},
            },
        ),
    ]
