# Generated by Django 6.0.3 on 2026-05-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0014_proximitycandidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristobject",
            name="last_sync_check",
            field=models.DateTimeField(
                blank=True,
                help_text="Data ostatniego sprawdzenia obiektu przez asynchronicznego stróża.",
                null=True,
                verbose_name="Ostatnia weryfikacja w OSM",
            ),
        ),
        migrations.CreateModel(
            name="OsmSyncConflict",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("field_name", models.CharField(max_length=50, verbose_name="Zmienione pole")),
                ("old_value", models.CharField(blank=True, max_length=500, null=True, verbose_name="Wartość w bazie")),
                ("new_value", models.CharField(blank=True, max_length=500, null=True, verbose_name="Propozycja z OSM")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Oczekujące na decyzję"),
                            ("ACCEPTED", "Zaakceptowane (Nadpisane)"),
                            ("REJECTED", "Odrzucone (Zachowano stare)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tourist_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_conflicts",
                        to="badges.touristobject",
                        verbose_name="Obiekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konflikt Danych OSM",
                "verbose_name_plural": "Konflikty Danych OSM",
                "db_table": "odznaki_osm_sync_conflict",
                "ordering": ["-created_at"],
            },
        ),
    ]
