# Generated by Django 6.0.3 on 2026-06-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0015_touristobject_last_sync_check_osmsyncconflict"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeNewsItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("change_date_str", models.CharField(max_length=50, verbose_name="Data z portalu")),
                (
                    "change_type",
                    models.CharField(
                        choices=[("ADDITION", "Nowa odznaka"), ("CHANGE", "Zmiana regulaminu")],
                        max_length=20,
                        verbose_name="Typ zmiany",
                    ),
                ),
                ("badge_name", models.CharField(max_length=255, verbose_name="Nazwa odznaki")),
                ("source_url", models.URLField(max_length=500, verbose_name="Źródło (Link)")),
                ("is_read", models.BooleanField(default=False, verbose_name="Przeczytane")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Aktualność Odznaki",
                "verbose_name_plural": "Radar Aktualności",
                "db_table": "odznaki_badge_news_item",
                "ordering": ["-created_at"],
                "unique_together": {("change_date_str", "change_type", "badge_name")},
            },
        ),
    ]
