# Generated by Django 6.0.3 on 2026-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0016_badgenewsitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristregionmodel",
            name="neighbors",
            field=models.ManyToManyField(blank=True, to="badges.touristregionmodel", verbose_name="Sąsiedzi"),
        ),
    ]
