# Generated by Django 6.0.3 on 2026-06-20 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0017_touristregionmodel_neighbors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="touristregionmodel",
            name="neighbors",
        ),
    ]
