# Generated by Django 6.0.3 on 2026-06-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0018_remove_touristregionmodel_neighbors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countrymodel",
            options={"verbose_name": "Państwo", "verbose_name_plural": "Państwa"},
        ),
        migrations.AlterModelOptions(
            name="macroregionmodel",
            options={"verbose_name": "Makroregion", "verbose_name_plural": "Makroregiony"},
        ),
        migrations.AlterModelOptions(
            name="mesoregionmodel",
            options={"verbose_name": "Mezoregion", "verbose_name_plural": "Mezoregiony"},
        ),
        migrations.AlterModelOptions(
            name="provincemodel",
            options={"verbose_name": "Prowincja", "verbose_name_plural": "Prowincje"},
        ),
        migrations.AlterModelOptions(
            name="subprovincemodel",
            options={"verbose_name": "Podprowincja", "verbose_name_plural": "Podprowincje"},
        ),
        migrations.AlterModelOptions(
            name="voivodeshipmodel",
            options={"verbose_name": "Województwo", "verbose_name_plural": "Województwa"},
        ),
        migrations.AddField(
            model_name="touristregionmodel",
            name="neighbors",
            field=models.ManyToManyField(blank=True, to="badges.touristregionmodel", verbose_name="Sąsiedzi"),
        ),
    ]
