# Generated by Django 6.0.3 on 2026-06-20 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0019_alter_countrymodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countrymodel",
            options={"managed": False, "verbose_name": "Państwo", "verbose_name_plural": "Państwa"},
        ),
        migrations.AlterModelOptions(
            name="macroregionmodel",
            options={"managed": False, "verbose_name": "Makroregion", "verbose_name_plural": "Makroregiony"},
        ),
        migrations.AlterModelOptions(
            name="mesoregionmodel",
            options={"managed": False, "verbose_name": "Mezoregion", "verbose_name_plural": "Mezoregiony"},
        ),
        migrations.AlterModelOptions(
            name="provincemodel",
            options={"managed": False, "verbose_name": "Prowincja", "verbose_name_plural": "Prowincje"},
        ),
        migrations.AlterModelOptions(
            name="subprovincemodel",
            options={"managed": False, "verbose_name": "Podprowincja", "verbose_name_plural": "Podprowincje"},
        ),
        migrations.AlterModelOptions(
            name="voivodeshipmodel",
            options={"managed": False, "verbose_name": "Województwo", "verbose_name_plural": "Województwa"},
        ),
        migrations.RemoveField(
            model_name="touristregionmodel",
            name="neighbors",
        ),
    ]
