# Generated by Django 6.0.3 on 2026-06-20 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0020_alter_countrymodel_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS odznaki_country_neighbors (id BIGSERIAL PRIMARY KEY, from_countrymodel_id BIGINT NOT NULL, to_countrymodel_id BIGINT NOT NULL, UNIQUE (from_countrymodel_id, to_countrymodel_id));
            CREATE TABLE IF NOT EXISTS odznaki_voivodeship_neighbors (id BIGSERIAL PRIMARY KEY, from_voivodeshipmodel_id BIGINT NOT NULL, to_voivodeshipmodel_id BIGINT NOT NULL, UNIQUE (from_voivodeshipmodel_id, to_voivodeshipmodel_id));
            CREATE TABLE IF NOT EXISTS odznaki_province_neighbors (id BIGSERIAL PRIMARY KEY, from_provincemodel_id BIGINT NOT NULL, to_provincemodel_id BIGINT NOT NULL, UNIQUE (from_provincemodel_id, to_provincemodel_id));
            CREATE TABLE IF NOT EXISTS odznaki_subprovince_neighbors (id BIGSERIAL PRIMARY KEY, from_subprovincemodel_id BIGINT NOT NULL, to_subprovincemodel_id BIGINT NOT NULL, UNIQUE (from_subprovincemodel_id, to_subprovincemodel_id));
            CREATE TABLE IF NOT EXISTS odznaki_macroregion_neighbors (id BIGSERIAL PRIMARY KEY, from_macroregionmodel_id BIGINT NOT NULL, to_macroregionmodel_id BIGINT NOT NULL, UNIQUE (from_macroregionmodel_id, to_macroregionmodel_id));
            CREATE TABLE IF NOT EXISTS odznaki_mesoregion_neighbors (id BIGSERIAL PRIMARY KEY, from_mesoregionmodel_id BIGINT NOT NULL, to_mesoregionmodel_id BIGINT NOT NULL, UNIQUE (from_mesoregionmodel_id, to_mesoregionmodel_id));
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS odznaki_country_neighbors;
            DROP TABLE IF EXISTS odznaki_voivodeship_neighbors;
            DROP TABLE IF EXISTS odznaki_province_neighbors;
            DROP TABLE IF EXISTS odznaki_subprovince_neighbors;
            DROP TABLE IF EXISTS odznaki_macroregion_neighbors;
            DROP TABLE IF EXISTS odznaki_mesoregion_neighbors;
            """,
        )
    ]
